const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let brand='all', compare=new Set();
const statusLabels={stock:'En stock',arrival:'Arrivage',reserved:'Réservé',out:'Rupture'};
function money(v){return v==null?'Prix à renseigner':new Intl.NumberFormat('fr-FR').format(v)+' F CFP TTC'}
function card(v){const inv=INVENTORY[v.id]||{};return `<article class="vehicle-card ${v.brand}" data-id="${v.id}"><div class="vehicle-visual">${v.image?`<img src="${v.image}" alt="${v.model}">`:`<div class="placeholder">${v.brand==='sea-doo'?'SD':'CA'}</div>`}</div><div class="vehicle-body"><div class="vehicle-meta"><span>${v.brandLabel} · ${v.year}</span><span class="status ${inv.status}">${statusLabels[inv.status]||''}</span></div><div class="vehicle-title">${v.model}</div><div class="spec-chips">${v.summary.map(x=>`<span class="chip">${x}</span>`).join('')}</div><div class="vehicle-meta"><span>${v.category}</span><span>${inv.color||''}</span></div><div class="price">${money(PRICES[v.id])}</div><div class="card-actions"><button class="btn primary" data-detail="${v.id}">Caractéristiques</button><button class="btn secondary ${compare.has(v.id)?'selected':''}" data-compare="${v.id}">${compare.has(v.id)?'Sélectionné':'Comparer'}</button></div></div></article>`}
function render(){const q=$('#search').value.toLowerCase(), st=$('#statusFilter').value; const rows=VEHICLES.filter(v=>{const inv=INVENTORY[v.id]||{};if(inv.active===false)return false;if(brand!=='all'&&v.brand!==brand)return false;if(st!=='all'&&inv.status!==st)return false;return !q||JSON.stringify(v).toLowerCase().includes(q)});$('#catalog').innerHTML=rows.map(card).join('')||'<p>Aucun modèle ne correspond.</p>';wire()}
function wire(){$$('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));$$('[data-compare]').forEach(b=>b.onclick=()=>toggleCompare(b.dataset.compare))}
function openDetail(id){const v=VEHICLES.find(x=>x.id===id),inv=INVENTORY[id]||{};let specs='';for(const [sec,rows] of Object.entries(v.specs)){specs+=`<section class="spec-section"><h3>${sec}</h3><div class="spec-table">${Object.entries(rows).map(([k,val])=>`<div class="spec-row"><span>${k}</span><b>${val}</b></div>`).join('')}</div></section>`}$('#detailContent').innerHTML=`<div class="detail-head"><div>${v.image?`<img src="${v.image}">`:`<div class="vehicle-visual"><div class="placeholder">${v.brand==='sea-doo'?'SD':'CA'}</div></div>`}</div><div><span class="brand-badge ${v.brand}">${v.brandLabel}</span><h2 class="detail-title">${v.model}</h2><p>${v.year} · ${v.category}</p><p>${inv.color||''}</p><div class="detail-price">${money(PRICES[id])}</div><p class="status ${inv.status}">${statusLabels[inv.status]||''}</p></div></div>${specs}`;$('#detailDialog').showModal()}
function toggleCompare(id){if(compare.has(id))compare.delete(id);else{if(compare.size>=3){alert('Vous pouvez comparer jusqu’à 3 modèles.');return}compare.add(id)}$('#compareCount').textContent=compare.size;render()}
function flatten(v){const o={};for(const [s,rows] of Object.entries(v.specs))for(const [k,val] of Object.entries(rows))o[`${s} — ${k}`]=val;return o}
function openCompare(){if(compare.size<2){alert('Sélectionnez au moins 2 modèles.');return}const vs=[...compare].map(id=>VEHICLES.find(v=>v.id===id));const flat=vs.map(flatten);const keys=[...new Set(flat.flatMap(o=>Object.keys(o)))];const rows=keys.map(k=>`<tr><td>${k}</td>${flat.map(o=>`<td>${o[k]??'—'}</td>`).join('')}</tr>`).join('');$('#compareContent').innerHTML=`<h2>Comparaison</h2><table class="compare-table"><thead><tr><th>Caractéristique</th>${vs.map(v=>`<th>${v.model}<br><small>${v.year}</small><br>${money(PRICES[v.id])}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table>`;$('#compareDialog').showModal()}
$$('.brand-tab').forEach(b=>b.onclick=()=>{$$('.brand-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');brand=b.dataset.brand;render()});$('#search').oninput=render;$('#statusFilter').onchange=render;$('#compareOpen').onclick=openCompare;$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());render();
